### PR TITLE
Feature/toolchain update

### LINKED ISSUE #83: Update toolchain

### PR DESCRIPTION
**Pull request by schrooom**
Closes #83.

Running with
> node version `16.3.0`
> npm version `7.17.0`

Possibly the deletion of `node_modules` might be necessary to solve some errors with `npm install`.

### CODE REVIEW

**Review by felixerdy — CHANGES_REQUESTED** [review]
Not working for me right now. I did the following steps:
- Deleted `node_modules`
- `npm install`
- `npm start`

Error:
```
››› npm start  

> simport-learning@0.0.1 start
> ng serve

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
⠋ Generating browser application bundles (phase: setup)...An unhandled exception occurred: Cannot find module 'ajv-keywords'
Require stack:
- /Users/felix/Documents/git/simport-learning-app/node_modules/mini-css-extract-plugin/node_modules/schema-utils/dist/validate.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/mini-css-extract-plugin/node_modules/schema-utils/dist/index.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/mini-css-extract-plugin/dist/index.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/mini-css-extract-plugin/dist/cjs.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular-devkit/build-angular/src/webpack/configs/styles.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular-devkit/build-angular/src/webpack/configs/index.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular-devkit/architect/node/index.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular/cli/models/architect-command.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular/cli/commands/serve-impl.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular/cli/utilities/json-schema.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular/cli/models/command-runner.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular/cli/lib/cli/index.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular/cli/lib/init.js
- /Users/felix/Documents/git/simport-learning-app/node_modules/@angular/cli/bin/ng
See "/private/var/folders/nn/mxz4g0655l9chn4kmlnrzh300000gn/T/ng-MZzzDs/angular-errors.log" for further details.
```

`npm install ajv-keywords` resulted in another error

My system:
```
››› node -v  
v16.4.0

››› npm -v   
7.18.1
```

It's working however when deleting `package-lock.json` beforehand

**Comment by schrooom** [comment]
> Not working for me right now. I did the following steps:
> 
> * Deleted `node_modules`
> * `npm install`
> * `npm start`
> 
> Error:
> 
> ```
> [...]
> ⠋ Generating browser application bundles (phase: setup)...An unhandled exception occurred: Cannot find module 'ajv-keywords'
> [...]
> ```

I updated the `package.json` and pinned the version for `ajv-keywords`, which did the trick for me. Could you kindly retry it yourself, @felixerdy? (see 396fb32)

**Comment by felixerdy** [comment]
Still not working for me ☹️ 
On `npm start` I'm getting

```
> simport-learning@0.0.1 start
> ng serve

An unhandled exception occurred: Cannot find module 'ajv/dist/compile/equal'
Require stack:
- /app/node_modules/webpack-dev-server/node_modules/ajv-keywords/dist/definitions/uniqueItemProperties.js
- /app/node_modules/webpack-dev-server/node_modules/ajv-keywords/dist/keywords/uniqueItemProperties.js
- /app/node_modules/webpack-dev-server/node_modules/ajv-keywords/dist/keywords/index.js
- /app/node_modules/webpack-dev-server/node_modules/ajv-keywords/dist/index.js
- /app/node_modules/webpack-dev-server/node_modules/schema-utils/src/validateOptions.js
- /app/node_modules/webpack-dev-server/node_modules/schema-utils/src/index.js
- /app/node_modules/webpack-dev-server/lib/Server.js
- /app/node_modules/@angular-devkit/build-webpack/src/webpack-dev-server/index.js
- /app/node_modules/@angular-devkit/build-webpack/src/index.js
- /app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /app/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /app/node_modules/@angular-devkit/architect/node/index.js
- /app/node_modules/@angular/cli/models/architect-command.js
- /app/node_modules/@angular/cli/commands/serve-impl.js
- /app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /app/node_modules/@angular/cli/utilities/json-schema.js
- /app/node_modules/@angular/cli/models/command-runner.js
- /app/node_modules/@angular/cli/lib/cli/index.js
- /app/node_modules/@angular/cli/lib/init.js
- /app/node_modules/@angular/cli/bin/ng
See "/tmp/ng-r73SeU/angular-errors.log" for further details.
```

Not only on my machine but also in docker container running `node:16` 

Maybe @noerw or @zven could check on their machines?

**Comment by zven** [comment]
For me, it works.

> node version `v16.4.0` (installed via `brew install node`)
> npm version `7.18.1`

I had to delete `node_modules` and `package-lock.json` beforehand.

**Comment by schrooom** [comment]
Did some further testing, the pinning of the few vulnerable packages to non-vulnerable versions causes the issue – therefore I left the vulnerable ones in for now and will keep an eye on it. Either way the number of vulnerabilities was reduced significantly by all those updates:

From `3 low, 9 moderate, 19 high, 2 critical` to `5 moderate, 4 high` (→ no critical ones anymore)

(Just to be safe: delete the `node_modules` one more time before testing .)

**Review by felixerdy — APPROVED** [review]

**Pull request merged**
