### PR TITLE
Feature/settings page

### LINKED ISSUE #130: Prepare settings and imprint page
The app is still lacking an imprint page (which we should have for our first study) and a place where we could list the used open source libraries and licenses. Those could be sub-pages of a settings page.
Please implement a settings page that can be opened from the upper right corner of the start screen (e.g. by clicking on a cog-icon). The user should be able to navigate back to the front page with an arrow icon that is located in the top left corner (please see existing pages in the app). On this page should be two options / buttons that open separate pages:
- an "Imprint" button that opens the imprint page
- an "Open source licenses" button that opens the license page
For now, it is sufficient if both pages contain Lorem ipsum text that we replace with meaningful text later (not part of this card). You could, for example, use https://loremipsum.io/generator/ to create some placeholder text.

To implement this feature, you'd need to familiarize yourself first with the basics of Angular (like creation and use of models, components, pages and navigation). Here, I'd suggest to try out the Angular "Tour of heroes" tutorial (https://angular.io/tutorial) and the Ionic/Angular tutorial (https://ionicframework.com/docs/angular/your-first-app). This will teach you some basic concepts that will help you for implement the settings and imprint page.

Todos:
- [x] Angular "Tour of heroes" tutorial (https://angular.io/tutorial)
- [x] Ionic/Angular tutorial (https://ionicframework.com/docs/angular/your-first-app)
- [x] add settings button to front page of app with cog icon
- [x] "Settings" page is opened on button press
- [x] "Settings" page allows to navigate back to previous page
- [x] button that opens "Imprint" page (filled with lorem ipsum text)
- [x] button that opens "Open source licenses" page (filled with lorm ipsum text)

Hints:
- When implementing the tutorials, it could make sense to track them in an own github repository where you commit you changes bit by bit.
- When working on the actual feature, please create an extra branch (e.g. "feature/settings-page") and commit your changes step by step with meaningful commit messages (e.g. `#130: add settings button to main page`).
- In case sth. is unclear, you are stuck or you feel that you need some feedback, please get in touch with one of us. :-)
- You can edit this comment to adjust the proposed todos in the list.

### PR DESCRIPTION
**Pull request by JuanFFranco**
#130

### CODE REVIEW

**Comment by schrooom** [comment]
It seems like you've created this branch on the base of a version of `feature/visualize-start-stop` / mixed in commits to #125 – thus mixing those two issues into one PR (even though there is a separate PR for `feature/visualize-start-stop`).

For reviewing card #130 and this PR this branch needs to have a clean state (= using our main branch `develop` as a base) – otherwise we would merge #125 (potentially incomplete, since `feature/visualize-start-stop` seems to have more commits?) and #130 at once.

**Comment by zven** [comment]
@JuanFFranco Have you tried to run the tests locally before and after merging the develop branch into feature/settings-page? There seems to be a provider missing somewhere although I can't tell if that one was missing already before merging.

**Comment by zven** [comment]
@JuanFFranco Since https://github.com/sitcomlab/simport-learning-app/issues/125 has been merged, there are now conflicts between the current state of the develop branch and this one. Could you merge the current dev state and resolve those conflicts?

**Comment by felixerdy** [comment]
Will be continued in #152

**Pull request closed without merging**
