### PR TITLE
Feature/update toolchain

### LINKED ISSUE #149: Updated toolchain and libraries

### PR DESCRIPTION
**Pull request by schrooom**
Closes #149

### CODE REVIEW

**Comment by felixerdy** [comment]
TBH I don't really like the big calendar date picker. I just played around with the standard date input and was able to create  this with the following code: 
```
<input
  type="date"
  [ngModel]="date | date: 'yyyy-MM-dd'"
  (ngModelChange)="date = $event"
  [value]="date | date: 'yyyy-MM-dd'"
/>
```
(check https://github.com/angular/angular/issues/8203#issuecomment-376479835 for the ngModel stuff)

Bildschirmfoto 2022-02-17 um 09 59 53

The following styles were applied to the input element:
```
min-width: fit-content;
background: transparent;
```

Of course, that's open for discussion. We also should take a look on how it looks like on Android and on english language devices

**Comment by schrooom** [comment]
> TBH I don't really like the big calendar date picker. I just played around with the standard date input and was able to create this with the following code:
> 
> [...] 
>
> Of course, that's open for discussion. We also should take a look on how it looks like on Android and on english language devices

I agree, thanks for looking into this – definitely looks better that way. I'll have a go with that :)

**Comment by schrooom** [comment]
The classic `input`-Tag looked a bit odd on Android, therefore I used the Ionic one. Makes this view a lot cleaner IMO – thanks again for the feedback! Ready to review once again :)

**Comment by felixerdy** [comment]
I don't know if I did something wrong but starting the location tracking is not working for me on this branch.

Steps to reproduce:
1. Location tracking on the `develop` branch is working on iOS Simulator
2. Checkout `feature/update-toolchain` branch and delete `node_modules`
3. Remove "simport-learning" app on iOS Simulator
4. Install dependencies
5. Run app on iOS Simulator
6. Result: No location access dialog but only a "simple" dialog which opens the app settings (where you can not enable location tracking)

| | |
|---|---|
| Bildschirmfoto 2022-02-18 um 11 20 08 |  Bildschirmfoto 2022-02-18 um 11 20 16 |

Maybe due to
```
Processing legacy "View Engine" libraries:
[...]
- @ionic-native/background-geolocation [module/esm5] (https://github.com/ionic-team/ionic-native.git)
[...]
Encourage the library authors to publish an Ivy distribution.
```
?

**Comment by schrooom** [comment]
> I don't know if I did something wrong but starting the location tracking is not working for me on this branch.
> 
> Steps to reproduce:
> 
> 1. Location tracking on the `develop` branch is working on iOS Simulator
> 2. Checkout `feature/update-toolchain` branch and delete `node_modules`
> 3. Remove "simport-learning" app on iOS Simulator
> 4. Install dependencies
> 5. Run app on iOS Simulator
> 6. Result: No location access dialog but only a "simple" dialog which opens the app settings (where you can not enable location tracking)
> 
> Bildschirmfoto 2022-02-18 um 11 20 08	Bildschirmfoto 2022-02-18 um 11 20 16
> Maybe due to
> 
> ```
> Processing legacy "View Engine" libraries:
> [...]
> - @ionic-native/background-geolocation [module/esm5] (https://github.com/ionic-team/ionic-native.git)
> [...]
> Encourage the library authors to publish an Ivy distribution.
> ```
> 
> ?

Good find! I accidentally removed a very small but crucial part in the background-service – this is now fixed. Additionally I fixed the missing translations, that you can see in your screenshot ;)

**Review by felixerdy — APPROVED** [review]

**Pull request merged**
